---

- name: run command
  shell: "{{ cmd }}" 
  args:
    chdir: "{{ project_path }}"
  environment:
    MIX_ENV: "{{ mix_env }}"
  register: cmd_output
  become: yes
  become_user: "{{ deployer }}"
  become_flags: "-i"

- debug: msg="{{ cmd_output.stdout_lines }}"
