---

- name: migrate database
  shell: "mix ecto.migrate" 
  args: 
    chdir: "{{ project_path }}"
  environment:
    MIX_ENV: "{{ mix_env }}"
  become: yes
  become_user: "{{ deployer }}"
  become_flags: "-i"
