---
- name: "install asdf"
  git: repo="https://github.com/HashNuke/asdf.git" dest="~/.asdf" update=yes
  become: yes
  become_user: "{{deployer}}"


- name: "source asdf in bashrc"
  lineinfile: dest="~/.bash_profile" create=yes line="source ~/.asdf/asdf.sh"
  become: yes
  become_user: "{{deployer}}"


- name: "add asdf plugins"
  command: "bash -lc 'asdf plugin-add {{item}} https://github.com/HashNuke/asdf-{{item}}.git'"
  register: command_result
  with_items:
    - nodejs
    - erlang
    - elixir
  become: yes
  become_user: "{{deployer}}"
  failed_when: "(not ('already added' or 'Cloning into') in command_result.stderr) and command_result.rc != 0"


- name: "add node.js release team's OpenPGP keys to main keyring"
  command: "bash ~/.asdf/plugins/nodejs/bin/import-release-team-keyring"
  become: yes
  become_user: "{{deployer}}"
