---
- name: "create deployer user"
  user: name="{{deployer}}" shell=/bin/bash
  become: yes

- name: "read authorized keys from remote user"
  command: "cat /home/{{ansible_user}}/.ssh/authorized_keys"
  register: "remote_authorized_keys"
  become: no

- name: "create .ssh dir for deployer"
  file: path="/home/{{ deployer }}/.ssh" state=directory
  become: yes
  become_user: "{{ deployer }}"

- name: "copy authorized keys to deployer user"
  shell: "echo '{{remote_authorized_keys.stdout}}' > /home/{{deployer}}/.ssh/authorized_keys"
  become: yes
  become_user: "{{ deployer }}"

- name: "chown the authorized_keys file"
  file: path="/home/{{deployer}}/.ssh" recurse=yes mode=0700 owner="{{ deployer }}"
  become: yes

- name: "ensure projects directory"
  file: path="~/projects" state=directory
  become: yes
  become_user: "{{ deployer }}"
