---
- name: "set npm jobs config"
  shell: "npm config set jobs {{ npm_config_jobs }}"
  args:
    chdir: "{{ project_path }}/{{ frontend_dir }}"
  become: yes
  become_user: "{{ deployer }}"
  become_flags: "-i"


- when: npm_config_install_production == True
  name: calculate npm install options
  set_fact: npm_install_options="--production"


- name: "fetch npm dependencies"
  shell: "npm install {{npm_install_options}}"
  args:
    chdir: "{{ project_path }}/{{ frontend_dir }}"
  become: yes
  become_user: "{{ deployer }}"
  become_flags: "-i"


- name: check for bower.json
  stat: path="{{ project_path }}/{{frontend_dir}}/bower.json"
  register: bower_json_file


- when: bower_json_file.stat.exists == True
  name: install bower dependencies
  shell: "$(npm bin)/bower install"
  args:
    chdir: "{{ project_path }}/{{ frontend_dir }}"
  become: yes
  become_user: "{{ deployer }}"
  become_flags: "-i"


- name: "build frontend assets"
  shell: "{{ frontend_build_command }}"
  args:
    chdir: "{{ project_path }}/{{ frontend_dir }}"
  become: yes
  become_user: "{{ deployer }}"
  become_flags: "-i"


- when: "post_frontend_build != False"
  name: "post-frontend-build command"
  shell: "{{ post_frontend_build }}"
  args:
    chdir: "{{ project_path }}"
  environment:
    MIX_ENV: "{{ mix_env }}"
  become: yes
  become_user: "{{ deployer }}"
  become_flags: "-i"

