---
- name: Update APT cache
  apt: update_cache=yes
  become: yes

- name: Ensure dependencies are installed
  apt: "pkg={{ item }} state=present"
  with_items:
    - build-essential
    - automake
    - libtool
  become: yes

- name: Clone libsass repository
  git:
    repo: https://github.com/sass/libsass.git
    dest: /usr/src/libsass
    accept_hostkey: yes
    depth: 1
    force: yes
  become: yes

- name: Clone saasc repository
  git:
    repo: https://github.com/sass/sassc.git
    dest: /usr/src/libsass/sassc
    accept_hostkey: yes
    depth: 1
    force: yes
  become: yes

- name: Compile libsass
  shell: make -C libsass --jobs={{ ansible_processor_cores }} chdir=/usr/src
  environment:
    BUILD: shared
  become: yes

- name: Compile sassc
  shell: make -C libsass --jobs={{ ansible_processor_cores }} sassc chdir=/usr/src
  environment:
    SASS_LIBSASS_PATH: /usr/src/libsass
  become: yes

- name: Copy libsass compiled libraries
  shell: 'cp -v /usr/src/libsass/lib/{{ item }} /usr/local/lib/{{ item }}'
  with_items:
    - libsass.a
    - libsass.so
  become: yes

- name: Copy sassc compiled binary file
  shell: 'cp -v /usr/src/libsass/sassc/bin/sassc /usr/local/bin/sassc'
  become: yes

- name: Setting sassc permissions
  file:
    path: /usr/local/bin/sassc
    mode: 755
  become: yes
