---
- name: "add postgres repository"
  apt_repository: repo="deb http://apt.postgresql.org/pub/repos/apt/ {{ ansible_distribution_release }}-pgdg main"
  become: yes


- name: "add postgres repository key"
  apt_key: url="https://www.postgresql.org/media/keys/ACCC4CF8.asc"
  become: yes


- name: "install postgres, libpq-dev, and postgis"
  apt: name="{{ item }}" update_cache=yes state=present
  with_items:
    - postgresql-9.6
    - libpq-dev
    - postgis
  become: yes


- name: install psycopg2 python module
  pip: name=psycopg2
  become: yes


- name: create postgres user for deployer
  postgresql_user:
    name: "{{ deployer }}"
    password: "{{ database_password }}"
    role_attr_flags: CREATEDB,SUPERUSER
  become_user: postgres
  become: yes


- name: "create database"
  postgresql_db: name="{{ database_name }}" encoding="UTF-8"
  become_user: postgres
  become: yes


- name: enable postgresql on reboot
  service: name=postgresql enabled=yes
  become: yes
